name: Rohitt Shinde.
description: Random stuff about code, and art.
meta_description: "A blog of Rohitt Shinde. Code and art."

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'blog.rohitt.com'
google_analytics: 'UA-58674260-1'
disqus: true
disqus_shortname: 'shinderohitt'

encoding: UTF-8
relative_permalinks: false

# Details for the RSS feed generator
url:            'http://blog.rohitt.com'
author:         'Rohitt Shinde'
authorTwitter:  'shinderohitt'

permalink:       /:year/:month/:title/

exclude: ["vendor"]

gems:
  - jekyll-paginate
  - github-pages

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
