name: Rohit Shinde
description:
meta_description: "A blog of Rohit Shinde"

aboutPage: true

markdown: kramdown
kramdown:
  input: GFM
  highlighter: rouge

highlighter: rouge

paginate: 200
baseurl: /
domain_name: 'rohitshinde.in'
google_analytics: 'UA-104099613-1'
disqus: true
disqus_shortname: 'shinderohitt'

encoding: UTF-8

# Details for the RSS feed generator
url:            'https://rohitshinde.in'
author:         'Rohit Shinde'
authorTwitter:  'shinderohitt'

permalink:       /:year/:month/:title/

exclude: ["vendor"]
future: true

gems:
  - jekyll-paginate
  - github-pages

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
