name: Rohitt Shinde.
description: Random stuff about code, and art.
meta_description: "A blog of Rohitt Shinde. Code and art."

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'shinderohitt.github.io'
google_analytics: 'UA-58674260-1'
disqus: true
disqus_shortname: 'shinderohitt'

# Details for the RSS feed generator
url:            'http://shinderohitt.github.io'
author:         'Rohitt Shinde'
authorTwitter:  'shinderohitt'

permalink:       /:year/:month/:title/

gems:
  - jekyll-paginate

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
