baseURL = "https://rohitshinde.in"
languageCode = "en-US"
title = "Rohit Shinde"
author = "Rohit Shinde"
theme = "hugo-bearblog"


# Generate a nice robots.txt for SEO
enableRobotsTXT = true

[params]
  title = "Rohit Shinde"
  description = "Personal website of Rohit Shinde"
  copyright = "Copyright © 2025 Rohit Shinde"
  dark = "auto"
  highlight = true
  hideMadeWithLine = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 3

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true


[markup.highlight]
      codeFences = true
      hl_Lines = ""
      lineNoStart = 1
      lineNumbersInTable = true
      tabWidth = 4
      style="solarized-light"
      pygmentsUseClasses = true
      pygmentsCodefences = true
